### ISSUE TITLE
Bot doesn't send messages to the chat

### ISSUE THREAD

**Issue by marinok** [iamwavecut/ngbot#4]
Hi!

I cloned your bot and followed "I'm too young to die" instruction. Docker works well, bot gets events and actions from group and private chats, but doesn't send replies. Command /lang ru doesn't work, for example. I started debugging and found that 'db.ChatMeta' returns nil in the Handle function (admin.go, line 30).

Could you, please, help with this issue :)

**Comment by iamwavecut** [comment]
Latest master commit is bugged, you can try rolling back to previous commit

**Comment by marinok** [comment]
The same result with previous commit (0683abcd8973ffe2bffb1b515db59a78416c40c3)

**Comment by iamwavecut** [comment]
Ok then... Please contact me t.me/WaveCut well figure it out

**Comment by iamwavecut** [comment]
`master` is broken for now. Use commit [d97f5e](https://github.com/iamwavecut/ngbot/commit/d97f5edf7da9296a1df369d11f5b25141e653ea7) if you want to fool around.

`git reset HEAD^2`

**Comment by iamwavecut** [comment]
Master should work OK now
